---
- name: RedHat | Include Secure Vars
  include_vars:
    file: ../defaults/secure.yml

- name: RedHat | Install Packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: RedHat | Enable Service {{ firewall_port }} in Firewalld
  firewalld:
    immediate: yes
    service: "{{ firewall_port }}"
    permanent: yes
    state: enabled

- name: RedHat | Copy {{ postfix_config_file }} Configuration File
  template:
    src: "{{ postfix_config_file }}.j2"
    dest: "/etc/postfix/{{ postfix_config_file }}"
    owner: root
    group: root
    mode: 0644
    force: yes
  notify:
  - restart postfix

- name: RedHat | Configure Postfix SASL Authentication 
  template:
    src: "{{ sasl_auth_file }}.j2"
    dest: "/etc/postfix/{{ sasl_auth_file }}"
    owner: root
    group: root
    mode: 0600
    force: yes
  notify:
  - restart postfix

- name: RedHat | postmap /etc/postfix/{{ sasl_auth_file }}
  command: postmap /etc/postfix/{{ sasl_auth_file }}
  register: postmap_output # Registers the command output.
  changed_when: postmap_output.rc != 0 # Uses the return code to define when the task has changed.

- name: RedHat | Start and Enable Service {{ systemd_service }}
  service:
    name: "{{ systemd_service }}"
    state: started
    enabled: yes
