---
- name: RedHat | Include Secure Vars
  ansible.builtin.include_vars:
    file: ../defaults/secure.yml

- name: RedHat | Install Packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: RedHat | Enable Service in Firewalld {{ firewall_port }}
  ansible.posix.firewalld:
    immediate: true
    service: "{{ firewall_port }}"
    permanent: true
    state: enabled

- name: RedHat | Copy Configuration File {{ postfix_config_file }}
  ansible.builtin.template:
    src: "{{ postfix_config_file }}.j2"
    dest: "/etc/postfix/{{ postfix_config_file }}"
    owner: root
    group: root
    mode: "0644"
    force: true
  notify:
    - Restart postfix

- name: RedHat | Configure Postfix SASL Authentication
  ansible.builtin.template:
    src: "{{ sasl_auth_file }}.j2"
    dest: "/etc/postfix/{{ sasl_auth_file }}"
    owner: root
    group: root
    mode: "0600"
    force: true
  notify:
    - Restart postfix

- name: RedHat | Run postmap /etc/postfix/{{ sasl_auth_file }}
  ansible.builtin.command: postmap /etc/postfix/{{ sasl_auth_file }}
  register: postmap_output # Registers the command output.
  changed_when: postmap_output.rc != 0 # Uses the return code to define when the task has changed.

- name: RedHat | Start and Enable Service {{ systemd_service }}
  ansible.builtin.service:
    name: "{{ systemd_service }}"
    state: started
    enabled: true
