---
## Default variables for the role. These variables have the lowest
## priority of any variables available, and can be easily overridden
## by any other variable, including inventory variables.

mysql_gpg_keys:
  - https://repo.mysql.com/RPM-GPG-KEY-mysql-2023
  - https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
  - https://repo.mysql.com/RPM-GPG-KEY-mysql

packages:
  - mysql-community-server
  - mysql-community-client
  - mysqltuner

systemd_service: "mysqld"

mysql_config_file: "/etc/my.cnf"
