---
- name: Include playbook RedHat
  include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Include playbook Debian
  include: setup-Debian.yml
  when: ansible_os_family == 'Debian'
