---
- name: RedHat | Configure OpenSSH Server
  vars:
    - sshd_subsystem: "/usr/libexec/openssh/sftp-server"
  block:
  - name: RedHat | Install Packages
    package:
      name: "{{ item }}"
      state: present
    loop: "{{ packages }}"

  - name: RedHat | Disable system-wide crypto policy usage for SSH
    lineinfile:
      path: /etc/sysconfig/sshd
      regexp: "^# CRYPTO_POLICY="
      line: CRYPTO_POLICY=
    when: ansible_distribution_major_version == "8"

  - name: RedHat | Copy {{ sshd_config_file }} Configuration File
    template:
      src: "{{ sshd_config_file }}.j2"
      dest: "/etc/ssh/{{ sshd_config_file }}"
      owner: root
      group: root
      mode: 0600
    notify:
    - restart sshd

  - name: RedHat | Check Services
    ansible.builtin.service_facts:

  - name: RedHat | Enable Service {{ firewall_port }} in Firewalld
    firewalld:
      immediate: yes
      service: "{{ firewall_port }}"
      permanent: yes
      state: enabled
    when: "'firewalld.service' in ansible_facts.services"
    ignore_errors: yes
