---
- name: RedHat | Disable SWAP because K8s up to v1.22 does work with swap enabled (1/2)
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: RedHat | Remove SWAP from fstab because K8s up to v1.22 does not work with swap enabled (2/2)
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: RedHat | Add the br_netfilter module
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: RedHat | Configure Sysctl Values
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ sysctl_config }}"

- name: RedHat | Remove firewalld/nftables from RHEL 8 and 9
  package:
    name: "{{ item }}"
    state: absent
  loop: "{{ packages_to_remove }}"
  when: (ansible_distribution_major_version == "8") or (ansible_distribution_major_version == "9")

- name: RedHat | Add Kubernetes Repository Sources
  yum_repository:
    file: "kubernetes"
    name: "kubernetes"
    description: "kubernetes"
    baseurl: "{{ k8s_repository_redhat }}"
    gpgcheck: yes
    gpgkey: "{{ k8s_gpg_key_redhat }}"
    enabled: yes
    #exclude: kubelet,kubeadm,kubectl
    skip_if_unavailable: yes

- name: RedHat | Install Dependencies
  package:
    name: "{{ item }}"
    state: present
    allow_downgrade: yes
  loop: "{{ dependencies }}"

- name: RedHat | Install Packages
  package:
    name: "{{ item }}"
    state: present
    allow_downgrade: yes
  loop: "{{ packages }}"

- name: RedHat | Print Message About cgroupDriver
  debug:
    msg: "In K8s v1.22, if the user is not setting the cgroupDriver field under KubeletConfiguration, kubeadm will default it to systemd."

- name: RedHat | Configure Kubelet Eviction Thresholds
  lineinfile:
    path: "{{ kubelet_file }}"
    state: present
    regexp: "^KUBELET_EXTRA_ARGS="
    line: "KUBELET_EXTRA_ARGS=--eviction-hard=memory.available<256Mi,nodefs.available<1Gi,imagefs.available<1Gi"

- name: RedHat | Start and Enable Service {{ systemd_service }}
  service:
    name: "{{ systemd_service }}"
    state: started
    enabled: yes

- name: RedHat | Deploy {{ modules_config_file }}
  template:
    src: "files/{{ modules_config_file }}"
    dest: "{{ modules_directory }}/{{ modules_config_file }}"
    owner: root
    group: root
    mode: 0644
    force: yes

- name: RedHat | Add the ip_tables module
  community.general.modprobe:
    name: ip_tables
    state: present

#
# Legacy configuration
# Configure firewall on RHEL 7
#
- name: RedHat | Configure firewalld on RHEL 7
  block:
  - name: RedHat | Open K8s firewall ports for master
    firewalld:
      immediate: yes
      permanent: yes
      state: enabled
      port: "{{ item }}/tcp"
    loop: "{{ k8s_firewall_ports_master }}"
    when: "'k8s_master' in group_names"

  - name: RedHat | Open K8s firewall ports for node
    firewalld:
      immediate: yes
      permanent: yes
      state: enabled
      port: "{{ item }}/tcp"
    loop: "{{ k8s_firewall_ports_node }}"
    when: "'k8s_node' in group_names"

  - name: RedHat | Open K8s firewall ports for CNI
    firewalld:
      immediate: yes
      permanent: yes
      state: enabled
      port: "{{ item }}/tcp"
    loop: "{{ k8s_firewall_ports_cni }}"

  - name: RedHat | Open K8s firewall ports for MetalLB - TCP
    firewalld:
      immediate: yes
      permanent: yes
      state: enabled
      port: "{{ item }}/tcp"
    loop: "{{ k8s_firewall_ports_metallb }}"

  - name: RedHat | Open K8s firewall ports for MetalLB - UDP
    firewalld:
      immediate: yes
      permanent: yes
      state: enabled
      port: "{{ item }}/udp"
    loop: "{{ k8s_firewall_ports_metallb }}"

  - name: RedHat | Enable Firewalld Masquerade
    firewalld:
      immediate: yes
      permanent: yes
      state: enabled
      masquerade: yes

  when: ansible_distribution_major_version == "7"
