---
- name: RedHat | Configure Sysctl Values
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ sysctl_config }}"

- name: RedHat | Install Prerequisites Packages
  package: 
    name: "{{ item }}"
    state: present
  loop: "{{ prerequisites_packages }}"

- name: RedHat | Add Docker Repository Sources
  yum_repository:
    file: "docker-ce-stable"
    name: "docker-ce-stable"
    description: "Docker CE Stable - $basearch"
    baseurl: "{{ docker_repository_redhat }}"
    gpgcheck: yes
    gpgkey: "{{ docker_gpg_key_redhat }}"
    enabled: yes

- name: RedHat | Install Packages
  package: 
    name: "{{ item }}"
    state: present
    allow_downgrade: yes
  loop: "{{ packages }}"

- name: RedHat | Start and Enable Service {{ systemd_service }}
  service:
    name: "{{ systemd_service }}"
    state: started
    enabled: yes

- name: RedHat | Copy {{ docker_daemon_config_file }} to Use systemd as cGroupDriver
  template:
    src: "files/{{ docker_daemon_config_file }}"
    dest: "/etc/docker/{{ docker_daemon_config_file }}"
    owner: root
    group: root
    mode: 0644
  notify:
  - restart docker

- name: RedHat | systemctl restart {{ systemd_service }}
  command: systemctl restart {{ systemd_service }}
