---
## Default variables for the role. These variables have the lowest
## priority of any variables available, and can be easily overridden 
## by any other variable, including inventory variables.

hosts_file: "/etc/hosts"
hosts_template: "hosts.j2"
