---
## Default variables for the role. These variables have the lowest
## priority of any variables available, and can be easily overridden
## by any other variable, including inventory variables.

packages:
  - tftp-server
  - syslinux
  - vsftpd
  - nfs-utils
  - nginx

systemd_services:
  - tftp
  - vsftpd
  - nfs-server
  - nginx

firewall_ports:
  - tftp
  - ftp
  - nfs
  - mountd
  - rpc-bind
  - http

nfs_selinux_booleans:
  - use_nfs_home_dirs
  - nfsd_anon_write

pasv_ftp_min_port: "60000"
pasv_ftp_max_port: "60029"

vsftpd_config_file: "vsftpd.conf"
nginx_config_file: "nginx.conf"

tftp_directory: "/var/lib/tftpboot"
ftp_directory: "/var/ftp/pub"
nfs_directory: "/var/nfs"
nginx_directory: "/var/www/html"

kickstart_file_rocky9_host: "rocky9-host-ks.cfg"
kickstart_file_rocky9_packer: "rocky9-packer-ks.cfg"
kickstart_file_rocky8_host: "rocky8-host-ks.cfg"
kickstart_file_rocky8_packer: "rocky8-packer-ks.cfg"
kickstart_file_ubuntu2004server: "ubuntu2004-server.seed"
kickstart_file_ubuntu2004desktop: "ubuntu2004-desktop.seed"

networkboot_directory_rocky9: "Rocky9"
networkboot_directory_rocky8: "Rocky8"
networkboot_directory_ubuntu2004server: "Ubuntu2004Server"
networkboot_directory_ubuntu2004desktop: "Ubuntu2004Desktop"

# Booleans to control whether media should be downloaded
download_pxe_boot_media: true
download_packer_media: true

# The kernel and initrd files from the Bionic netboot.tar.gz archive
ubuntu_2004_netboot_linux: "http://archive.ubuntu.com/ubuntu/dists/focal-updates/main/installer-amd64/current/legacy-images/netboot/ubuntu-installer/amd64/linux"
ubuntu_2004_netboot_initrd: "http://archive.ubuntu.com/ubuntu/dists/focal-updates/main/installer-amd64/current/legacy-images/netboot/ubuntu-installer/amd64/initrd.gz"

# These are used for PXE boot
pxe_boot_media:
  - name: "ubuntu2004server"
    iso_url: "https://releases.ubuntu.com/20.04/ubuntu-20.04.5-live-server-amd64.iso"
    iso_sha256: "5035be37a7e9abbdc09f0d257f3e33416c1a0fb322ba860d42d74aa75c3468d4"
    source_directory: "{{ nfs_directory }}/{{ networkboot_directory_ubuntu2004server }}/"
    netboot_directory: "{{ tftp_directory }}/networkboot/{{ networkboot_directory_ubuntu2004server }}/"
    setype: "nfs_t"
    mounted_src: "/mnt/casper"
    pxeboot_files:
      - initrd
      - vmlinuz
  - name: "ubuntu2004desktop"
    iso_url: "https://releases.ubuntu.com/20.04/ubuntu-20.04.5-desktop-amd64.iso"
    iso_sha256: "2980570ea889f3467a04df15c8421ef1dc80ecef7bb37243da97f5714cf3f8ef"
    source_directory: "{{ nfs_directory }}/{{ networkboot_directory_ubuntu2004desktop }}/"
    netboot_directory: "{{ tftp_directory }}/networkboot/{{ networkboot_directory_ubuntu2004desktop }}/"
    setype: "nfs_t"
    mounted_src: "/mnt/casper"
    pxeboot_files:
      - initrd
      - vmlinuz
  - name: "rocky8"
    iso_url: "https://download.rockylinux.org/pub/rocky/8/isos/x86_64/Rocky-8.10-x86_64-dvd1.iso"
    iso_sha256: "642ada8a49dbeca8cca6543b31196019ee3d649a0163b5db0e646c7409364eeb"
    source_directory: "{{ ftp_directory }}/pxe/{{ networkboot_directory_rocky8 }}/"
    netboot_directory: "{{ tftp_directory }}/networkboot/{{ networkboot_directory_rocky8 }}/"
    setype: "public_content_t"
    mounted_src: "/mnt/images/pxeboot"
    pxeboot_files:
      - initrd.img
      - vmlinuz
  - name: "rocky9"
    iso_url: "https://download.rockylinux.org/pub/rocky/9/isos/x86_64/Rocky-9.4-x86_64-dvd.iso"
    iso_sha256: "e20445907daefbfcdb05ba034e9fc4cf91e0e8dc164ebd7266ffb8fdd8ea99e7"
    source_directory: "{{ ftp_directory }}/pxe/{{ networkboot_directory_rocky9 }}/"
    netboot_directory: "{{ tftp_directory }}/networkboot/{{ networkboot_directory_rocky9 }}/"
    setype: "public_content_t"
    mounted_src: "/mnt/images/pxeboot"
    pxeboot_files:
      - initrd.img
      - vmlinuz

# These are used for Packer
packer_media:
  - iso_url: "https://download.rockylinux.org/pub/rocky/9/isos/x86_64/Rocky-9.4-x86_64-boot.iso"
    iso_sha256: "c7e95e3dba88a1f68fff8b7d4e66adf6f76ac4fba2e246a83c46ab79574c78a8"
  - iso_url: "https://download.rockylinux.org/pub/rocky/8/isos/x86_64/Rocky-8.10-x86_64-boot.iso"
    iso_sha256: "203744a255ea6579e49ca7f7f0f17e2fda94e50945d8183a254490e454c7c5b4"
