---
- name: RedHat | Create Static VPN Route
  become: true
  ansible.builtin.template:
    src: "{{ network_template }}"
    dest: "/etc/sysconfig/network-scripts/route-br0"
    owner: root
    group: root
    mode: "0644"
  when: "'kvm' in group_names"
  ignore_errors: true
  register: ignore_errors_register
