---
- name: RedHat | Configure Sysctl Values
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ sysctl_config }}"

- name: RedHat | Install Prerequisites Packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ prerequisites_packages }}"

- name: RedHat | Add Docker Repository Sources
  ansible.builtin.yum_repository:
    file: "docker-ce-stable"
    name: "docker-ce-stable"
    description: "Docker CE Stable - $basearch"
    baseurl: "{{ docker_repository_redhat }}"
    gpgcheck: true
    gpgkey: "{{ docker_gpg_key_redhat }}"
    enabled: true

- name: RedHat | Remove Docker Packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  loop:
    - docker-ce
    - docker-ce-cli

- name: RedHat | Install Packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    allow_downgrade: true
  loop: "{{ packages }}"

- name: RedHat | Create Directory {{ systemd_service }}
  ansible.builtin.file:
    path: /etc/{{ systemd_service }}
    state: directory
    mode: "0755"

- name: RedHat | Generate Containerd Config
  ansible.builtin.shell: containerd config default > /etc/{{ systemd_service }}/config.toml
  become: true
  register: containerd_output # Registers the command output.
  changed_when: containerd_output.rc != 0 # Uses the return code to define when the task has changed.

- name: RedHat | Enable Systemd cgroup driver for Containerd Runtime
  ansible.builtin.lineinfile:
    path: /etc/{{ systemd_service }}/config.toml
    search_string: "SystemdCgroup = false"
    line: "            SystemdCgroup = true"
  become: true

- name: RedHat | Start and Enable Service {{ systemd_service }}
  ansible.builtin.service:
    name: "{{ systemd_service }}"
    state: started
    enabled: true

- name: RedHat | Systemd Restart {{ systemd_service }}
  ansible.builtin.systemd:
    name: "{{ systemd_service }}"
    state: restarted
