---
- name: RedHat | Include Secure Vars
  include_vars:
    file: ../defaults/secure.yml

- name: RedHat | Install Packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: RedHat | Configure Sysctl Values
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ sysctl_config }}"

- name: RedHat | Allow VRRP Traffic to Pass Between the Keepalived Nodes
  firewalld:
    immediate: yes
    permanent: yes
    state: enabled
    rich_rule: "rule protocol value=vrrp accept"

- name: RedHat | Configure Master Keepalived Server
  template:
    src: "{{ keepalived_config_file }}.master.j2"
    dest: "/etc/keepalived/{{ keepalived_config_file }}"
    owner: root
    group: root
    mode: 0644
    force: yes
  when: "'dns1' in group_names"
  notify:
  - restart keepalived

- name: RedHat | Configure Slave Keepalived Server
  template:
    src: "{{ keepalived_config_file }}.slave.j2"
    dest: "/etc/keepalived/{{ keepalived_config_file }}"
    owner: root
    group: root
    mode: 0644
    force: yes
  when: "'dns2' in group_names"
  notify:
  - restart keepalived

- name: RedHat | Start and Enable Service {{ systemd_service }}
  service:
    name: "{{ systemd_service }}"
    state: started
    enabled: yes
