---
- name: RedHat | Include Secure Vars
  ansible.builtin.include_vars:
    file: ../defaults/secure.yml

- name: RedHat | Install Packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: RedHat | Enable Service in Firewalld {{ firewall_port }}
  ansible.posix.firewalld:
    immediate: true
    service: "{{ firewall_port }}"
    permanent: true
    state: enabled

- name: RedHat | Enable DHCP Failover Port in Firewalld {{ firewall_dhcp_failover_port }}
  ansible.posix.firewalld:
    immediate: true
    port: "{{ firewall_dhcp_failover_port }}/tcp"
    permanent: true
    state: enabled

- name: RedHat | Configure Master DHCP Server
  when: "'dns1' in group_names"
  block:
    - name: RedHat | Copy {{ dhcpd_config_file }}
      ansible.builtin.template:
        src: "{{ dhcpd_config_file }}.master.j2"
        dest: "/etc/dhcp/{{ dhcpd_config_file }}"
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart dhcpd

- name: RedHat | Configure Slave DHCP Server
  when: "'dns2' in group_names"
  block:
    - name: RedHat | Copy {{ dhcpd_config_file }}
      ansible.builtin.template:
        src: "{{ dhcpd_config_file }}.slave.j2"
        dest: "/etc/dhcp/{{ dhcpd_config_file }}"
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart dhcpd

- name: RedHat | Start and Enable Service {{ systemd_service }}
  ansible.builtin.service:
    name: "{{ systemd_service }}"
    state: started
    enabled: true
