---
- name: RedHat | Include Secure Vars
  include_vars:
    file: ../defaults/secure.yml

- name: RedHat | Install Packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: RedHat | Enable Service {{ firewall_port }} in Firewalld
  firewalld:
    immediate: yes
    service: "{{ firewall_port }}"
    permanent: yes
    state: enabled

- name: RedHat | Enable Service DHCP Failover in Firewalld
  firewalld:
    immediate: yes
    port: "647/tcp"
    permanent: yes
    state: enabled

- name: RedHat | Configure Master DHCP Server
  block:
    - name: RedHat | Copy {{ dhcpd_config_file }}
      template: 
        src: "{{ dhcpd_config_file }}.master.j2"
        dest: "/etc/dhcp/{{ dhcpd_config_file }}"
        owner: root
        group: root
        mode: 0644
      notify:
      - restart dhcpd
  when: "'dns1' in group_names"

- name: RedHat | Configure Slave DHCP Server
  block:
    - name: RedHat | Copy {{ dhcpd_config_file }}
      template: 
        src: "{{ dhcpd_config_file }}.slave.j2"
        dest: "/etc/dhcp/{{ dhcpd_config_file }}"
        owner: root
        group: root
        mode: 0644
      notify:
      - restart dhcpd
  when: "'dns2' in group_names"

- name: RedHat | Start and Enable Service {{ systemd_service }}
  service:
    name: "{{ systemd_service }}"
    state: started
    enabled: yes
