---
- name: RedHat | Create Swap File {{ swap_file }}
  command: dd if=/dev/zero of="{{ swap_file }}" bs=1M count="{{ swap_size }}"
  args:
    creates: "{{ swap_file }}"
  notify:
    - make swap filesystem

- name: RedHat | Flush Handlers
  ansible.builtin.meta: flush_handlers

- name: RedHat | Set Swap File Permissions
  file:
    path: "{{ swap_file }}"
    state: file
    owner: root
    group: root
    mode: 0600

- name: RedHat | Add Swap to /etc/fstab
  mount:
    src: "{{ swap_file }}"
    name: "none"
    fstype: "swap"
    opts: "sw,nofail"
    dump: "0"
    passno: "0"
    state: "present"

- name: RedHat | swapon -a
  command: swapon -a

- name: RedHat | Set Sysctl vm.swappiness to {{ sysctl_swappiness }}
  sysctl:
    name: vm.swappiness
    value: "{{ sysctl_swappiness }}"
    state: present
