---
- name: RedHat | Disable sleep on Laptop Lid Close
  ansible.builtin.lineinfile:
    path: "{{ systemd_file }}"
    state: present
    regexp: "^HandleLidSwitch="
    line: "HandleLidSwitch=ignore"
