---
## Default variables for the role. These variables have the lowest
## priority of any variables available, and can be easily overridden
## by any other variable, including inventory variables.

packages:
  - curl
  - epel-release
  - glibc-langpack-en
  - htop
  - iotop
  - policycoreutils-devel
  - policycoreutils-python-utils
  - psmisc
  - rsync
  - setroubleshoot-server
  - tar
  - telnet
  - vim
  - wget
  - yum-utils
