---
- name: Linux | Create "{{ hosts_file }}" File
  become: true
  template:
    src: "{{ hosts_template }}"
    dest: "{{ hosts_file }}"
    owner: root
    group: root
    mode: "0644"
  ignore_errors: yes
