---
- name: Linux | Create File {{ hosts_file }}
  become: true
  ansible.builtin.template:
    src: "{{ hosts_template }}"
    dest: "{{ hosts_file }}"
    owner: root
    group: root
    mode: "0644"
  ignore_errors: true
  register: ignore_errors_register
