---
users:
  - name: ansible
    password: "defined in secure.yml as user_password"
  - name: tom
    password: "defined in secure.yml as user_password"

sudo_group_redhat: "wheel"
sudo_group_debian: "sudo"
