---
- name: RedHat | Install Packages
  package: 
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: RedHat | Enable Service {{ firewall_port }} in Firewalld
  firewalld:
    immediate: yes
    service: "{{ firewall_port }}"
    permanent: yes
    state: enabled

- name: RedHat | Copy {{ chrony_conf_file }} Configuration File
  template: 
    src: "{{ chrony_conf_file }}.peer1.j2"
    dest: "/etc/{{ chrony_conf_file }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart chrony
  when: "'dns1' in group_names"

- name: RedHat | Copy {{ chrony_conf_file }} Configuration File
  template: 
    src: "{{ chrony_conf_file }}.peer2.j2"
    dest: "/etc/{{ chrony_conf_file }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart chrony
  when: "'dns2' in group_names"

- name: RedHat | Start and Enable Service {{ systemd_service }}
  service:
    name: "{{ systemd_service }}"
    state: started
    enabled: yes
