---
## Default variables for the role. These variables have the lowest
## priority of any variables available, and can be easily overridden
## by any other variable, including inventory variables.

packages:
  - epel-release
  - snapd

systemd_service: "snapd"

certbot_dns_plugin: "certbot-dns-cloudflare"
