---
- name: Create Users
  hosts: k8s
  remote_user: root
  gather_facts: true
  roles:
    - hl.users

- name: Configure Kubernetes Hosts
  hosts: k8s
  become: true
  gather_facts: true
  roles:
    - hl.sshd
    - hl.resolvconf
    - hl.timezone
    - hl.hardening
    - hl.common
    - hl.node-exporter
    - hl.containerd
    - hl.k8s
...
