---
- name: Create Users
  hosts: raspberrypi
  remote_user: root
  gather_facts: yes
  roles:
    - hl.users

- name: Configure RaspberryPi Hosts
  hosts: raspberrypi
  become: yes
  gather_facts: yes
  roles:
    - hl.sshd
    - hl.timezone
    - hl.pihole-exporter
...

