---
- name: Upgrade Packages
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: RedHat | Upgrade all packages, excluding kernel
      ansible.builtin.yum:
        name: '*'
        state: latest
        exclude: 'kernel*'
      when: ansible_os_family == 'RedHat'
...
